version: '3.2'

services:
  scrapy-py:
    build:
      context: cib_order/
    environment:
      URL1: ${URL1}
      CIB_USERNAME: ${CIB_USERNAME}
      CIB_PASS: ${CIB_PASS}
    networks:
      - scrapynet
    depends_on:
      - splash-scrapy
    

  splash-scrapy:
    build:
      context: splash-scrapy/
    ports:
      - "8050:8050"
    networks:
      - scrapynet

networks:
  scrapynet:
    driver: bridge
